
baseURL = "https://wangloo.github.io/"
title = "BLOG"
theme = "puer"

# 是否使用 git 信息
enableGitInfo = true
# 是否使用 emoji 代码
enableEmoji = true

[frontmatter]
  # 左边意为，变量 .LastMod 将会被赋值为右边数组中最先找到的的日期值
  lastmod = ['lastmod', ':git', ':fileModTime', 'date', 'publishDate']

[markup]
  [markup.highlight]
    anchorLineNos = false     # 行号格式化为<span>
    codeFences = true         # 代码围栏, 不启用高亮无效
    guessSyntax = true        # 自动推断高亮语言
    hl_Lines = ''             # 突出显示某些特定的行
    hl_inline = false         # 高亮 inline code, ver>=0.101.0
    lineAnchors = ''          #　与 anchorLineNos 配合
    lineNoStart = 1           # 行号开始
    lineNos = true            # 是否显示行号
    lineNumbersInTable = false # 生成html中分开行号和代码
    noClasses = true          
    noHl = false
    style = 'dracula'
    tabWidth = 4
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true # 启用markdown渲染器对于内敛html支持

    
[outputs]
  home = ["HTML", "RSS", "JSON"]


weight = 2
[[menu.main]]
url = "/tags"
name = "Tags"
weight = 3
[[menu.main]]
url = "/posts"
name = "所有文章"
weight = 1
[[menu.main]]
url = "/index.xml"
name = "RSS Feed"
weight = 4