
baseURL = "https://wangloo.github.io/"
title = "BLOG"
theme = "puer"


[markup]
  [markup.highlight]
    anchorLineNos = false     # 行号格式化为<span>
    codeFences = true         # 代码围栏, 不启用高亮无效
    guessSyntax = true        # 自动推断高亮语言
    hl_Lines = ''             # 突出显示某些特定的行
    hl_inline = false         # 高亮 inline code, ver>=0.101.0
    lineAnchors = ''          #　与 anchorLineNos 配合
    lineNoStart = 1           # 行号开始
    lineNos = true            # 是否显示行号
    lineNumbersInTable = false # 生成html中分开行号和代码
    noClasses = true          
    noHl = false
    style = 'vs'
    tabWidth = 4


    
[outputs]
  home = ["HTML", "RSS", "JSON"]


weight = 2
[[menu.main]]
url = "/tags"
name = "Tags"
weight = 3
[[menu.main]]
url = "/posts"
name = "所有文章"
weight = 1
[[menu.main]]
url = "/index.xml"
name = "RSS Feed"
weight = 4