baseURL = "https://wangloo.github.io/blog/"
languageCode = "en-us"
title = "Soben's Secret Base "
theme = "diary"
copyright = "@2019 Notepadium."
enableGitInfo = true
enableEmoji = true

[params]
  AuthorName = 'Soben Wang'
  GitHubuser = 'wangloo'
  Subtitle = '花有重开日, 人无再少年'
  enableGitalk = true
  enableReadingTime=true

[frontmatter]
  date = ['date', 'lastmod']
  lastmod = [':git', 'lastmod', 'date']

[[menu.main]]
url = "/categories"
name = "Categories"
weight = 3

[[menu.main]]
url = "/tags"
name = "Tags"
weight = 2

[[menu.main]]
url = "/posts"
name = "Archive"
weight = 1

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokailight"
    tabWidth = 4

  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2

[params.gitalk]
  owner = "wangloo"
  repo = "blogcomments_gitalk"
  client_id = "12dfb0f809e5e6afde3d"
  client_secret = "72aaf5660b3a7b43b0bffb4d683a605a7ea65dad"
